name: 'Terraform Azure Deployment'

on:
  push:
    branches:
      - Terraform-AVDALZ0updates

jobs:
  build:
    name: 'Deploy to Azure'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Apply'
      run: terraform apply -auto-approve
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_USE_OIDC: true
